#!/bin/bash

set -e

pushd "$(dirname "$0")" > /dev/null
SCRIPT_DIR="$(pwd)"
popd > /dev/null
DIST_DIR=$SCRIPT_DIR/dist

browserify $SCRIPT_DIR/index.js -o $DIST_DIR/polybool.js
uglifyjs $DIST_DIR/polybool.js --comments > $DIST_DIR/polybool.min.js
